Lm show h2console link
ucsb-cs156-s24/proj-courses-s24-4pm-1 pull request #30
Opened 2024-05-24 00:17 UTC by miguel-luis9

FEATURE: H2 Console option on navbar #29

Depending on SHOW_H2_CONSOLE_ENABLED, it will show H2 Console

2024-05-24 18:41 UTC, pconrad requested changes
Please remove commented out lines.
See: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-29 19:54 UTC, miguel-luis9 commented on src/main/resources/application-production.properties
> +# app.showH2ConsoleEnabled=${SHOW_H2_CONSOLE_ENABLED:${env.SHOW_H2_CONSOLE_ENABLED:false}}
I apologize for the late reply but I took out the commented lines.

2024-05-29 20:41 UTC, ericknee submitted a review, later dismissed
LGTM - no more comments in code

2024-05-29 20:58 UTC, pconrad approved these changes
LGTM

2024-05-29 20:58 UTC, merged