Added component/tests for Upload Grade History Job
ucsb-cs156-s24/proj-courses-s24-4pm-1 pull request #53
Opened 2024-05-30 00:40 UTC by ericknee

Fixes Issue #18 
Under the Manage Jobs tab, the Update Grade Info now has a button to upload the grade history.

Before:
<img width="564" alt="Screenshot 2024-05-29 at 5 39 38 PM" src="https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-1/assets/91811005/475e1ebf-a3ac-4bfb-9531-6d250c209809">

After:
<img width="1437" alt="Screenshot 2024-05-29 at 5 38 59 PM" src="https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-1/assets/91811005/f087f833-4546-4438-8a38-d084a32c6d65">

Dokku Deployment: https://project-ericknee-dev.dokku-01.cs.ucsb.edu/admin/jobs

2024-05-30 01:23 UTC, phamaiden approved these changes
LGTM

2024-05-30 10:20 UTC, monicatrinh1 approved these changes
LGTM!

2024-05-30 23:55 UTC, pconrad requested changes
Commented out code

2024-05-30 23:55 UTC, pconrad commented on frontend/src/tests/pages/AdminJobsPage.test.js
> +  });
Commented out code

2024-05-31 00:05 UTC, ericknee commented on frontend/src/tests/pages/AdminJobsPage.test.js
> +  });
Fixed

2024-05-31 00:55 UTC, merged