Make PersonalSchedule Form Description Optiona;
ucsb-cs156-s24/proj-courses-s24-4pm-1 pull request #54
Opened 2024-05-30 01:12 UTC by phamaiden

In this PR, I made the personal schedule form more user friendly by making the description field optional.
Closes #51 

In the video below, I demonstrate the new personal schedule form. As you can see the add form no longer requires a description and the personal schedule index page correctly displays the new schedule with no description. Similarly, the edit form doesn't require a description
https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-1/assets/92133253/0dd734c4-4683-4fdc-8a21-0ea1daf4985a

2024-05-30 01:42 UTC, Frank404NotFound submitted a review, later dismissed
LGTM

2024-05-30 05:35 UTC, ericknee submitted a review, later dismissed
LGTM

2024-05-30 23:57 UTC, pconrad requested changes
Please remove the unrelated code from the PR

2024-05-30 23:57 UTC, pconrad commented on frontend/src/main/pages/CourseDetails/CourseDetailsIndexPage.js
> +import GradeHistoryTable from "main/components/GradeHistory/GradeHistoryTable";
Unrelated change.  Should not be in this PR

2024-05-30 23:57 UTC, pconrad commented on frontend/src/main/pages/CourseDetails/CourseDetailsIndexPage.js
> +
Unrelated code should not be in this PR

2024-06-02 20:05 UTC, pconrad commented on frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesCreatePage.test.js
> +    //const quarterField = document.querySelector("#PersonalScheduleForm-quarter");
Commented out code ... please remove

2024-06-02 20:06 UTC, pconrad commented on frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesCreatePage.test.js
> +    //const selectQuarter = getByLabelText("Quarter")
Commented out code.  Please remove

2024-06-02 20:06 UTC, pconrad commented on frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesCreatePage.test.js
> +    //userEvent.selectOptions(selectQuarter, "20124");
Pls remove commented out code.

2024-06-02 20:06 UTC, pconrad commented on frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesCreatePage.test.js
> +    //expect(setQuarter).toBeCalledWith("20124"); //need this and axiosMock below?
Pls remove commented out code.

2024-06-02 22:41 UTC, pconrad commented
Deployed at https://courses-qa.dokku-01.cs.ucsb.edu/

2024-06-03 15:50 UTC, pconrad approved these changes
LGTM.  Will deploy on courses-qa to test before merging

2024-06-03 20:09 UTC, merged